### ISSUE TITLE
Rustfmt the codebase

### ISSUE THREAD

**Issue by aleksanb** [utkarshkukreti/select.rs#14]
Have you considered using [rustfmt](https://github.com/rust-lang-nursery/rustfmt)?
I noticed my vim-plugin automatically changing formatting in files while contributing to the project,
so i disabled it for the time being.
It can be ran for the entire project with `cargo fmt` after installing it.

**Comment by utkarshkukreti** [comment]
Good idea. I tried `rustfmt` a long time ago when it had some major bugs in the formatting logic as well as bugs that turned working code into non-working code, so I didn't use it. I just installed the latest `rustfmt` and the output seems to be nice and all the tests pass. I've also enabled it in my editor to run on every save from now on.
