### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by bluecereal** [utkarshkukreti/select.rs#31]
`Document::from_read()` exists here in the repo but not on crates.io, and they both have the same version number!  But they are different, so I thought they should be labeled as such (v0.3.1).  There must be some other changes as well?  

I hope I'm not being nitpicky here, as that is not my intention :)

**Comment by utkarshkukreti** [comment]
Sorry for the late reply. That function (and many other things) were added after 0.3.1 but I never released a new version after that (and so didn't update the version in Cargo.toml). I've released 0.4.0 now: https://crates.io/crates/select/0.4.0. Hope that helps!

**Comment by bluecereal** [comment]
Thanks!
