### ISSUE TITLE
New crate release

### ISSUE THREAD

**Issue by lukaspustina** [utkarshkukreti/select.rs#33]
Hi,

thanks for your crate which works beautiful for my use case; especially `descendant` is very useful. That said, the last release `0.3.0` does not support it yet.

Would you mind creating a new release and publish it crates.io. Currently this prevents me from publishing my dependant crate.

Thanks,
Lukas

**Comment by utkarshkukreti** [comment]
Just released 0.4.0: https://crates.io/crates/select/0.4.0. Hope that helps! Which crate are you going to release btw? I'd love to have a look!

**Comment by lukaspustina** [comment]
Thanks for publishing the new release.

I'm working on a little pet project that's going to make some tasks I frequently do easier and accessible from the CLI. And I use it to actually do some more Rust :) See for yourself: https://github.com/lukaspustina/rat
