### ISSUE TITLE
Add nightly warning

### ISSUE THREAD

**Issue by Ealhad** [utkarshkukreti/select.rs#52]
select.rs uses `#![feature]` which is a nightly-only feature.

Maybe it should be mentionned somewhere?

**Comment by utkarshkukreti** [comment]
The `feature` tags were only used in tests and benchmarks at the time you opened the issue, not when you were just using this crate as a dependency. I upgraded the tests to no longer use `feature`. The benchmarks still require it as the `test` crate is unstable. Anyways you shouldn't need nightly to use this library in your project.
