### ISSUE TITLE
Are you still developing this?

### ISSUE THREAD

**Issue by svenstaro** [utkarshkukreti/select.rs#56]
There haven't been any commits since over a year and I'm wondering whether @utkarshkukreti is still developing this. @utkarshkukreti, if you're reading this, do you plan to keep developing/maintaining this library?

**Comment by awulkan** [comment]
I am also wondering this. I found this library through a tutorial, but I'm hesitant in using something that's no longer maintained.

**Comment by utkarshkukreti** [comment]
I just merged PRs which upgrade the dependencies and released v0.4.3. I'm no longer using this library in any real project so I don't have much time to maintain it. I'll try my best to merge PRs that fix bugs. I'm also open to adding another person to merge bug fixes and make releases on crates.io!

**Comment by awulkan** [comment]
Okey, thanks for letting us know. :)

**Comment by svenstaro** [comment]
Thanks for the info.
