### ISSUE TITLE
How to pass a Selection into a function?

### ISSUE THREAD

**Issue by vm** [utkarshkukreti/select.rs#6]
Hi!

Was wondering if you could explain a bit how to do something like this signature.
```rust
fn parse_row(row: Selection) -> Option<String>
```
For now I am getting lifetime errors that I'm not able to fix using the source code. Let me know, thanks!

**Comment by utkarshkukreti** [comment]
What error are you getting? Does this work:

```
fn parse_row<'a>(row: Selection<'a>) -> Option<String> {
    Some("foo".into())
}
```

?

**Comment by vm** [comment]
That helped! Sorry about that, looks like all I forgot to do was do ```impl<'a> X<'a>``` instead of ```impl X<'a>```. Thanks again for a great library!
